
### CLIENTES: PETICION POST REGISTRO CLIENTE
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Esthefany", 
    "apellidos": "Ortega",
    "telefono": 917854747, 
    "direccion": "calle Villanueva 5", 
    "email": "juanperez@gmail.com"
}

### CLIENTES: PETICION GET DETALLE CLIENTE
GET http://localhost:3000/api/clientes/5


### CLIENTES: PETICION LOGIN
POST http://localhost:3000/api/clientes/login
Content-Type: application/json

{
    "email": "jp@gmail.com",
    "password": 1234
}


### PRODUCTOS: PETICION GET PARA OBTENER TODOS LOS PRODUCTOS
GET http://localhost:3000/api/productos

### PRODUCTOS: PETICION GET PARA OBTENER PRODUCTO POR ID
GET http://localhost:3000/api/productos/2


### PRODUCTOS: INCLUIR PRODUCTO A FAVORITOS SEGUN ID CLIENTE
POST http://localhost:3000/api/productos/favoritos
Content-Type: application/json

{
    "fk_id_cliente": 86, 
    "fk_id_producto":3
}


### ADMIN: PETICION GET OBTENER LISTA DE PEDIDOS PENDIENTES DE ENTREGA
GET http://localhost:3000/api/adminpedidos/



### CLIENTE: PETICION PARA CREAR UN NUEVO PEDIDO
POST http://localhost:3000/api/pedidos/nuevo
Content-Type: application/json

{
    "cantidad":11,
    "fecha_entrega":"2020-09-06",
    "precio_total": 7.50,
    "id_cliente":5,
    "direccion":"Calle gran via",
    "descripcion": "1 kg fresas",
    "estado":"realizado"
}


### PEDIDOS: PETICION POST OBTENER LISTA DE PEDIDOS PENDIENTES DE ENTREGA
POST http://localhost:3000/api/pedidos/pendientes

### PEDIDOS: PETICION POST OBTENER LISTA DE PEDIDOS REALIZADOS
POST http://localhost:3000/api/pedidos/realizados

###PEDIDOS: PETICION POST PARA OBTENER TODOS LOS PEDIDOS
GET http://localhost:3000/api/pedidos

###PEDIDOS: PETICION POST OBTENER PEDIDOS SEGUN ID DE CLIENTE
GET http://localhost:3000/api/clientes/pedidos/77




### ADMIN: PETICION GET OBTENER LISTADO DE CLIENTES
GET http://localhost:3000/api/admin

###
POST http://localhost:3000/api/clientes/token/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRlSWQiOjc3LCJjcmVhdGVkQXQiOjE1OTk2NDI3OTYsImV4cGlyZWRBdCI6MTU5OTY0MzY5NiwiaWF0IjoxNTk5NjQyNzk2fQ.lTcgnP8v3nDHJ17cdnJdZGcuj4NzGUowEWC0p44ENO0"
}
