
### CLIENTES: PETICION POST REGISTRO CLIENTE
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Esthefany", 
    "apellidos": "Ortega",
    "telefono": 917854747, 
    "direccion": "calle Villanueva 5", 
    "email": "juanperez@gmail.com"
}

### CLIENTES: PETICION GET DETALLE CLIENTE
GET http://localhost:3000/api/clientes/5


### CLIENTES: PETICION LOGIN
POST http://localhost:3000/api/clientes/login
Content-Type: application/json

{
    "email": "jp@gmail.com",
    "password": 0
}
### ADMIN: PETICION PARA CREAR UN NUEVO PEDIDO
POST http://localhost:3000/api/admin
Content-Type: application/json

{
    "id_pedido":3,
    "cantidad":010,
    "fecha_entrega":"2020-09-05",
    "precio_total": 6.50,
    "id_cliente":1
}


### ADMIN: PETICION GET OBTENER LISTA DE PEDIDOS PENDIENTES DE ENTREGA
POST http://localhost:3000/api/admin

### ADMIN: PETICION GET OBTENER LISTADO DE CLIENTES
GET http://localhost:3000/api/admin



### PRODUCTOS: PETICION GET PARA OBTENER TODOS LOS PRODUCTOS
GET http://localhost:3000/api/productos

### PRODUCTOS: PETICION GET PARA OBTENER PRODUCTO POR ID
GET http://localhost:3000/api/productos/2

###PEDIDOS: PETICION POST PARA OBTENER TODOS LOS PEDIDOS
POST http://localhost:3000/api/admin